project_name: supercronic

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
kos:
  - repository: ghcr.io/kidager/supercronic
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    annotations:
      title: "{{ .ProjectName }}"
      description: "{{ .ProjectName }}"
      licenses: "MIT"
nfpms:
- maintainer: Jacem Chaieb <jacem@chaieb.dev>
  description: Supercronic Fork
  homepage: https://github.com/kidager/supercronic
  license: MIT
  formats:
    - deb
    - rpm
    - apk
